version: "3.9"

services:
  api:
    build: .
    container_name: api_container
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${POSTGRES_PASSWORD}@${DATABASE_HOSTNAME}:${DATABASE_PORT}/${POSTGRES_DB}?schema=public
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
volumes:
  postgres_data: